package Application.Enums;

public enum LearningStates {
    INITIALIZED,
    HIDDEN_LAYER_WEIGHTS_GENERATE,
    INPUT_VECTOR_ATTACH_PHASE_ONE,
    COMPETITION_PHASE_ONE,
    UPDATING_HIDDEN_LAYER_WEIGHTS,
    PHASE_TWO_INITIALIZED,
    OUTPUT_LAYER_WEIGHTS_GENERATE,
    INPUT_VECTOR_ATTACH_PHASE_TWO,
    COMPETITION_PHASE_TWO,
    UPDATING_OUTER_LAYER_WEIGHTS,
    LEARNING_FINISHED
}
